### PR TITLE
Dem viz

### PR DESCRIPTION
**Pull request by nehabhomia**
**Overview**
This pull request introduces essential code setup, project structure, and data preprocessing steps. It also includes a key visualisation added to the **`demo-viz.py`** file. The visualisation created for the [demographic data](https://datacommons.morrisanimalfoundation.org/demographic-data) page is a bar graph with age buckets in years on the X-axis and the counts of dogs on the Y-axis. This is created using the Seaborn library.

**Next Steps**
With this foundation in place, we are now well-equipped to proceed with further data visualisation efforts. The next step for this would be to add the other visualisations that are present on this webpage along with the data to power the static graphics.

**Screenshot**
age_count

### CODE REVIEW

**Comment by anotherpatrickcollins** [comment]
Neha this looks great! I had just a couple small tweaks that might help it match some of our styling. 

I'm going to go off this visualization to make these visual updates...
image

- [ ] Remove title from chart (we do the title and the blue line in HTML on the page)
- [ ] Add bold and all-caps styling to all labels (both scale labels and axis labels)
- [ ] Change font of all labels to Bunday Sans (fonts in a zip file [Bunday Sans Complete for Neha.zip](https://github.com/morrisanimalfoundation/grls-visualizations/files/12717286/Bunday.Sans.Complete.for.Neha.zip))

Also I wanted to note that the changes above I think will cover almost all of the visualizations going forward so we likely won't do these over and over or anything! :)

**Comment by nehabhomia** [comment]
> * [ ]  Add bold and all-caps styling to all labels (both scale labels and axis labels)

Should I leave the units (counts/years) in the labels or remove them?

**Comment by anotherpatrickcollins** [comment]
I think we want to leave the units! Thanks for clarifying!

**Comment by lkacenja** [comment]
I was able to run this visualization code locally and it works as advertised. I think all of the feedback from Patrick has been resolved and the code style is excellent. Seems like we could merge this PR anytime. Thanks @nehabhomia and @anotherpatrickcollins !

**Comment by greggles** [comment]
Thanks for the work on this, everyone!

**Pull request merged**
